// src/config/permissions.js

export const PERMISSIONS = {
  /* ================= PATIENT ================= */
  PATIENT_VIEW_AI_RESULTS: "PATIENT_VIEW_AI_RESULTS",
  PATIENT_DOWNLOAD_REPORTS: "PATIENT_DOWNLOAD_REPORTS",

  /* ================= DOCTOR ================= */
  DOCTOR_VIEW_PATIENT_SUMMARY: "DOCTOR_VIEW_PATIENT_SUMMARY",
  DOCTOR_WRITE_CONSULTATION_NOTES: "DOCTOR_WRITE_CONSULTATION_NOTES",
  DOCTOR_OVERRIDE_AI: "DOCTOR_OVERRIDE_AI",

  /* ================= ADMIN ================= */
  ADMIN_VIEW_AUDIT_LOGS: "ADMIN_VIEW_AUDIT_LOGS",
  ADMIN_MANAGE_USERS: "ADMIN_MANAGE_USERS",
  ADMIN_CONFIGURE_AI: "ADMIN_CONFIGURE_AI",
};
