export const AUDIT_ACTIONS = {
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGOUT: "LOGOUT",

    PASSWORD_RESET_REQUESTED: "PASSWORD_RESET_REQUESTED",
    PASSWORD_RESET_COMPLETED: "PASSWORD_RESET_COMPLETED",


    AI_ANALYSIS_RUN: "AI_ANALYSIS_RUN",
    AI_ANALYSIS_TRIGGERED: "AI_EMERGENCY_TRIGGERED",

    PROFILE_UPDATED: "PROFILE_UPDATED",
    PROFILE_CREATED: "PROFILE_CREATED",

    APPOINTMENT_CREATED: "APPOINTMENT_CREATED",
    APPOINTMENT_STATUS_CHANGED: "APPOINTMENT_STATUS_CHANGED",

    CHAT_MESSAGE_SENT: "CHAT_MESSAGE_SENT",
    CONSENT_ACCEPTED: "CONSENT_ACCEPTED",

    USER_DEACTIVATED: "USER_DEACTIVATED",
    USER_DATA_EXPORTED: "USER_DATA_EXPORTED",
    DATA_RETENTION_PURGE: "DATA_RETENTION_PURGE",

    OTP_SENT: "OTP_SENT",
    OTP_VERIFIED: "OTP_VERIFIED",
};